baseurl = "https://kavinkumar999.github.io"
languageCode = "en-us"
title = "Kavin Kumar"
theme = "hugo-tania"
paginate = 6

[params]
  # Emoji will show before the blog title on site navbar.
  titleEmoji  = "😎"

  # Logo will show before the blog title on site navbar.
  titleLogo = ""

  # Enable float footnotes.
  # Default to true
  # enableFootnotes = false

  siteName = "Hugo Tania is Amazing"
  siteDesc = "Hugo is Absurdly Fast!"
  author = "Hugo Tania"

  [params.colorScheme]
    # Enable toggle colorScheme
    # Default to true
    toggle = true
    # Default colorScheme
    # Default to auto
    # default = auto

  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow = 10

  # Show your social information with icon on index bio with `_index.md` content.
  [params.socialOptions]
    dev-to = ""
    email = "kavinkumarnkm007@gmail.com"
    facebook = ""
    github = "https://github.com/kavinkumar999"
    instagram = ""
    linkedin = "https://www.linkedin.com/in/kavinkumar999/"
    medium = ""
    stack-overflow = ""
    steam = ""
    telegram = ""
    twitter = "https://twitter.com/kavinkumar999"
    twitch = ""
    whatsapp = ""
  
  # Comments settigns
  [params.comments]
    enabled = false
    provider = "disqus"

[menu]
[[menu.header]]
  name = "About"
  url = "#about"
[[menu.header]]
  name = "Experience"
  url = "#Experience"
# [[menu.header]]
#   name = "Blog"
#   url = "/blog/"

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true
  [markup.goldmark.renderer]
    unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]